// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPG0tG_qGVUQaaxdprIeYXF9lVONBvn9E',
    appId: '1:298634740911:web:efdd9bce760a71e98f805a',
    messagingSenderId: '298634740911',
    projectId: 'house-manager-bf593',
    authDomain: 'house-manager-bf593.firebaseapp.com',
    storageBucket: 'house-manager-bf593.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2yGQZoIawfGXjAZOCftLDAi6nVMUz4U',
    appId: '1:298634740911:android:43202ac2b431885c8f805a',
    messagingSenderId: '298634740911',
    projectId: 'house-manager-bf593',
    storageBucket: 'house-manager-bf593.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB-VLokQB_M-2ki4Ep3_6J1goOa99IlV4',
    appId: '1:298634740911:ios:b6c0582f9e677ec38f805a',
    messagingSenderId: '298634740911',
    projectId: 'house-manager-bf593',
    storageBucket: 'house-manager-bf593.firebasestorage.app',
    iosBundleId: 'com.example.houseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB-VLokQB_M-2ki4Ep3_6J1goOa99IlV4',
    appId: '1:298634740911:ios:b6c0582f9e677ec38f805a',
    messagingSenderId: '298634740911',
    projectId: 'house-manager-bf593',
    storageBucket: 'house-manager-bf593.firebasestorage.app',
    iosBundleId: 'com.example.houseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPG0tG_qGVUQaaxdprIeYXF9lVONBvn9E',
    appId: '1:298634740911:web:88e0f45baf192f148f805a',
    messagingSenderId: '298634740911',
    projectId: 'house-manager-bf593',
    authDomain: 'house-manager-bf593.firebaseapp.com',
    storageBucket: 'house-manager-bf593.firebasestorage.app',
  );
}
